### ISSUE TITLE
Failed to compile on Ubuntu 14.04 due to gcc<5 (4.9.4)

### ISSUE THREAD

**Issue by YaYaB** [beniz/deepdetect#256]
When trying to compile the following error is obtained:
`
/deepdetect/src/httpjsonapi.cc:356:20: error: 'put_time' is not a member of 'std'
       LOG(INFO) << std::put_time(std::localtime(&t), "%c %Z") << " - " << access_log << std::endl;
                    ^
/deepdetect/src/httpjsonapi.cc:357:24: error: 'put_time' is not a member of 'std'
     else LOG(ERROR) << std::put_time(std::localtime(&t), "%c %Z") << " - " << access_log << std::endl;
                        ^
make[2]: *** [src/CMakeFiles/ddetect.dir/httpjsonapi.cc.o] Error 1
make[1]: *** [src/CMakeFiles/ddetect.dir/all] Error 2
make: *** [all] Error 2
`

This is due to the fact that `put_time` is not implemented for gcc <5. 
` if (code == 200 || code == 201)
      LOG(INFO) << std::put_time(std::localtime(&t), "%c %Z") << " - " << access_log << std::endl;
else LOG(ERROR) << std::put_time(std::localtime(&t), "%c %Z") << " - " << access_log << std::endl;
`
I was able to compile by commenting those lines.

**Comment by beniz** [comment]
OK, confirmed, http://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc, we'll patch with an alternative for gcc < 5 unless you already have one to share, e.g. http://stackoverflow.com/questions/37421747/is-there-a-builtin-alternative-to-stdput-time-for-gcc-5

**Comment by beniz** [comment]
Fixed, thanks for the report!
